name: Build and Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - dev

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container: node:18

    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: sentrydiscord
          POSTGRES_PASSWORD: password
          POSTGRES_DB: sentrydiscord
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U sentrydiscord -d sentrydiscord"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # - name: Wait for PostgreSQL to be ready
      #   run: |
      #     docker exec -i $(docker ps -q -l) psql -U sentrydiscord -d sentrydiscord -c 'SELECT 1'

      # For more information, see https://docs.npmjs.com/cli/ci.html
      - name: Install dependencies
        run: npm i

      - name: Create schema db
        run: npx prisma migrate deploy

      - name: build
        run: npx browserslist@latest --update-db && npm run build

      - name: Install Docker
        run: |
          sudo apt update
          sudo apt install -y docker.io
          sudo systemctl start docker
          sudo systemctl enable docker

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/sentrydiscord:latest
